### ISSUE TITLE
missing typescript types

### ISSUE THREAD

**Issue by elranu** [ethereumjs/merkle-patricia-tree#102]
On the compiler options please add `"declaration": true`:
example:

`{
  "extends": "@ethereumjs/config-tsc",
  "compilerOptions": {
    "outDir": "./dist",
    "declaration": true
  },
  "include": ["src/**/*.ts"],`

**Comment by gasiortomasz** [comment]
This project's `tsconfig.json` expands on this file `https://github.com/ethereumjs/ethereumjs-config/blob/master/packages/ethereumjs-config-tsc/tsconfig.json` which has declaration flag set to true.

Weirdly enough I don't see declaration file after doing `yarn add merkle-patricia-tree` in my project

**Comment by s1na** [comment]
The typescript migration has not yet been released. That's why you're not seeing the declaration files. We've been mostly busy with the istanbul HF and this has had lower priority. Will get back to it soon.

**Comment by ryanio** [comment]
Thanks for your patience. The TypeScript migration will be released in v4.0.0 (#111).
