### ISSUE TITLE
Getting empty Buffer

### ISSUE THREAD

**Issue by tpmccallum** [ethereumjs/merkle-patricia-tree#31]
Hi,
I am documenting the Ethereum database structure 
![Here](https://github.com/tpmccallum/ethereum_database_research_and_testing/blob/master/leveldb/diagrams/ethereum_database.jpg)
and 
![here](https://github.com/tpmccallum/ethereum_database_research_and_testing/blob/master/leveldb/leveldb.md)

When I run the following code on my Ethereum Private Network I just get an empty buffer.
```
//requirements
var Trie = require('merkle-patricia-tree');
var levelup = require('levelup');
var leveldown = require('leveldown');
var rlp = require('rlp');
//set the database variable
var db = levelup(leveldown('/home/timothymccallum/gethDataDir/geth/chaindata'));
//set the genesis state root variable
var root = '0xe403429877a3fd13eb3da17503af458dd0741ec3b617f2eaf2338ca945edb0e2';
//set the trie variable
var trie = new Trie(db, root);
//set the variable tim which is my account address
var tim = new Buffer('0xb7714bd73152a27939914c644fb7471966378626', 'hex');
//get results from leveldb
trie.get(tim, function (err, val) {
  var decoded = rlp.decode(val);
  console.log(decoded);
});
```

Please let me know if you have any suggestions as well as useful links and documentation. I am looking to explore the entire workings of Ethereum database.

Thank you

**Comment by holgerd77** [comment]
Don't put the ``0x`` in your string when you create a new Buffer object.

Executing the Buffer creation in the Node console just gives ``<Buffer >`` as result.
