### ISSUE TITLE
Add tests for the proofs

### ISSUE THREAD

**Issue by axic** [ethereumjs/merkle-patricia-tree#34]
Merging #15 test coverage dropped from 87% to 81%. Would be nice to achieve close 100% :)

**Comment by holgerd77** [comment]
Hmm, wonder why coverage for ``proof.js`` is so bad https://coveralls.io/builds/14875747/source?filename=proof.js, there were actually various tests in the PR and achieving something around 5% is definitely too low, maybe it's the type of test execution?

**Comment by holgerd77** [comment]
Have checked, proof-related functions are in the normal coverage range and coverage is back to 89%, likely solved along integrating the dedicated `proof.js` file into `BaseTrie`. Will close.
