### ISSUE TITLE
Binary tree support

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/merkle-patricia-tree#41]
Data structures in Ethereum sharding will use a binary instead of a hex tree for shorter merkle proofs, see e.g. the ``Chunk tree`` description for ``Collations`` in the [sharding phase 1 spec](https://ethresear.ch/t/sharding-phase-1-spec/1407).

It should be analyzed if this library can easily be adopted to also support binary tree structures (first guess: just change the maximum number of child nodes).

Or if e.g. another tree implementation is already existing (e.g. https://github.com/dfinity/js-dfinity-radix-tree, also consider license compatibility), that would better serve the needs for sharding.

**Comment by zmitton** [comment]
seems to be worth a rewrite using promises. Just my 2 cents :)

**Comment by holgerd77** [comment]
Issue written with somewhat outdated assumptions and context, will close in favor of #121
