### ISSUE TITLE
Refactor: Use ES6 classes and extends keyword instead of util.inherits

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/merkle-patricia-tree#44]
The current way the different Trie class objects are constructed is not very readable, furthermore the use of ``util.inherits`` in Node [is discouraged](https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor).

This should be reworked to use ``ES6`` classes, constructors together with the ``extends`` keyword to inherit properties and methods.

**Comment by alextsg** [comment]
I can take a look at this

**Comment by holgerd77** [comment]
Hi Alex, just discovered that people are working on a pretty interesting and advanced fork of this library. Have started a discussion on that here: https://github.com/ethereumjs/merkle-patricia-tree/issues/54.

Maybe wait with this, would like to see where we are going there. If you want, you can also have a look at the fork from RainBlock, I think it should be possible to take many of the changes done there back into the library here.

**Comment by alextsg** [comment]
Ah ok. Thanks for the heads up @holgerd77

**Comment by s1na** [comment]
Thanks to @alextsg, most of the library has been ported to ES6 classes in #57 and #61. What remains now is `trieNode`. I was also wondering as to the purpose of `secureInterface` and `checkpointInterface`, why are they not implemented in `SecureTrie` and `CheckpointTrie` respectively?

**Comment by s1na** [comment]
The whole code base has been now ported to ES6 classes, see #57, #61, #71 and #73.
