### ISSUE TITLE
update checkpointing API

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/merkle-patricia-tree#58]
The current check-pointing API isn't the best and it is inefficient. The API could be simplified. Instead of `checkpoint`, `commit`  and `revert` there should be a single `commit` or [`flush`](https://github.com/ipld/js-ipld-graph-builder/blob/master/docs/index.md#flush)  function that writes everything to the DB and returns the resulting state root. Instead of `checkpoint` and `commit` we should have a functional API such as [this](https://www.npmjs.com/package/functional-red-black-tree). This relegates the functionality of `checkpoint` and `revert` to JS's GC which will have better performance then manually tracking the different referenced states.

**Comment by bit-warrior** [comment]
@wanderer i was thinking of working on this issue. Need more details about what is expected to be done. Looked into the code , `checkpoint`, `commit`  and `revert` have different purpose, can you plz give a little more detail on how to get that in one function `commit` or `flush`

**Comment by holgerd77** [comment]
Checkpointing has been substantially reworked in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1030 and https://github.com/ethereumjs/ethereumjs-monorepo/pull/1035, will close here (issue is also pretty old).
