### ISSUE TITLE
Extract db-related logic from baseTrie

### ISSUE THREAD

**Issue by s1na** [ethereumjs/merkle-patricia-tree#67]
In addition to MPT logic, `BaseTrie` also has methods for the underlying key-value db. This logic can be extracted to a separate class, to make `BaseTrie` more readable and reduce coupling. The methods include `getRaw`, 'putRaw`, 'batchNodes`, etc.

**Comment by holgerd77** [comment]
Makes sense.

**Comment by s1na** [comment]
`CheckpointTrie` tries to implement checkpointing by inheriting `BaseTrie`. During #73 I noticed that this might not be the best design, and this manifests in `_enterCpMode` and `_exitCpMode` where methods of `BaseTrie` are patched dynamically.

I think after extracting DB-related logic to a separate class, the checkpointing mechanism could be moved to this class. This would remove the need for patching methods dynamically, all other implementations of `Trie` (including `SecureTrie`) could use checkpointing without explicitly inheriting `CheckpointTrie`, and it would be more easy to reason about.

**Comment by holgerd77** [comment]
👍

**Comment by holgerd77** [comment]
Closed by #74.
